#!perl

# DATE
# VERSION

# FRAGMENT id=shcompgen-hint command=_cpanm-script

use strict;
use warnings;

use HTTP::Tiny;

for (@ARGV) {
    next unless /\A[A-Za-z0-9_][A-Za-z0-9_-]*\z/;
    my $resp = HTTP::Tiny->new->get("https://metacpan.org/pod/$_");
    unless ($resp->{success} and $resp->{content} =~ m!<a itemprop="downloadUrl" href="[^"]+/([^/]+/[^"]+)">!) {
        warn "Can't get distribution path for script '$_': $resp->{status} - $resp->{reason}\n";
        next;
    }
    $_ = $1;
}

print join(" ", "cpanm", @ARGV), "\n" if $ENV{DEBUG};
system {"cpanm"} "cpanm", @ARGV;

# ABSTRACT: Install modules from CPAN (via script name)
# PODNAME:

=head1 DESCRIPTION

L<cpanm-script> is a simplistic wrapper over L<cpanm>. This command:

 % cpanm-script -n csvutil

will cause B<cpanm-script> to search for the release tarball that contains the
script (currently via scraping C<https://metacpan.org/pod/SCRIPTNAME>) and will
then run:

 % cpanm -n PERLANCAR/App-CSVUtils-0.002.tar.gz

That's about it.

=cut
